### ISSUE TITLE
this Project is not CBT enough

### ISSUE THREAD

**Issue by ScorchedDesire** [Nrmot-GithubRepo/Project-CBT#41]
add jenny mod and Yuuka Kazami

**Comment by Higuys153** [comment]
> add jenny mod

WE CANT ITs INCOMPATIBLE

**Comment by Nrmot** [comment]
Go ahead and deobfuscate Jenny mod, then change the code then recompile it, I dare you all to try the pain of making Jenny mod compatible with moreplanets since one of the entities uses the same fucking ID as one from the Jenny Mod 
Or better yet if you find the moreplanets repository fork it and change the IDs of the conflicting ID 122
